name: main_in_foodfeast
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.1+2

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_launcher_icons: ^0.12.0
  webview_flutter: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
